app: distinct-subsequences

type: practices

logging:
  enabled: true

imagePullSecrets:
  - name: docker-registry-creds

containerPort: 8080

autoscaling:
  qa:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPU: 90
  prod:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPU: 90

resources:
  qa:
    limits:
      cpu: 300m
      memory: 300Mi
  prod:
    limits:
      cpu: 500m
      memory: 600Mi
